import turtle

desenho = turtle.Turtle()

desenho.penup ()
desenho.left (90)
desenho.forward (200)
desenho.left (90)
desenho.forward (100)
desenho.color ("black", "#3A74B0")
desenho.begin_fill ()
desenho.pendown ()
desenho.left (90)
desenho.forward (280)
desenho.left (90)
desenho.forward (300)
desenho.left (90)
desenho.forward (280)
desenho.left (90)
desenho.forward (300)
desenho.end_fill ()
desenho.penup ()
desenho.home ()
desenho.pendown ()
desenho.color ("black", "#C82626")
desenho.begin_fill ()
desenho.forward (100)
desenho.left (135)
desenho.forward (75)
desenho.home ()
desenho.end_fill ()
desenho.color ("black", "#E1B400")
desenho.begin_fill ()
desenho.left (270)
desenho.forward (80)
desenho.left (90)
desenho.forward (100)
desenho.left (90)
desenho.forward (80)
desenho.home ()
desenho.end_fill ()
desenho.penup ()
desenho.left (270)
desenho.forward (80)
desenho.left (90)
desenho.forward (35)
desenho.pendown ()
desenho.color ("black", "#D87E00")
desenho.begin_fill ()
desenho.left (90)
desenho.forward (60)
desenho.left (-90)
desenho.forward (30)
desenho.left (270)
desenho.forward (60)
desenho.end_fill ()

turtle.done()