import pandas as pd

df = pd.read_csv("OnePieceArcs.csv")
df.set_index ("Arc", inplace= True)
print (df.shape)
print (df.columns)
print (df.dtypes)
print (df.isnull().sum())
print (df.describe())
print (df['Start onChapter'].median())
print (df['TotalChapters'].median())
print (df['TotalPages'].median())
print (df['Start onEpisode'].median())
print (df['TotalEpisodes'].median())
print (df['TotalMinutes(avg 24)'].median())
print(df['Manga%'].value_counts())
print(df['Anime%'].value_counts())
print (df["TotalChapters"].max ())
print (df["TotalMinutes(avg 24)"].min ())
print (df["TotalEpisodes"].sum ())
print (df["TotalPages"].mean ())
print (df["TotalChapters"].sum ())