import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.set_index ("PassengerId", inplace= True)
df.head (12)
print (df.head(10))
print (df.tail(10))
print (df.info())
print (df.columns)
print (df.values)
print (df.loc [1])
print (df.loc[[1, 2, 3]])
print (df.loc[[1, 2, 3], ["Name", "Sex", "Age"]])
print (df.loc [10: 20])
print (df.loc [10: 20: 2])
print (df.loc [10: 20, ["Name", "Sex", "Age"]])
print (df.query ("Age > 20"))
print (df.query ("Age > 20 and Sex== 'male'"))
print (df.describe ())